# Generated by Django 4.2.2 on 2023-06-12 03:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GPTproject', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registration',
            name='address',
        ),
        migrations.RemoveField(
            model_name='registration',
            name='date_of_birth',
        ),
        migrations.RemoveField(
            model_name='registration',
            name='user',
        ),
        migrations.AddField(
            model_name='registration',
            name='email',
            field=models.EmailField(default='', max_length=254),
        ),
        migrations.AddField(
            model_name='registration',
            name='password',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='registration',
            name='username',
            field=models.CharField(default='', max_length=100),
        ),
    ]
